---
title: "Day 5 Lecture"
output: html_document
---

# Homework 3 Review

# Practice 4 Review

# Graphics overview

http://accidental-art.tumblr.com/

## Two systems

  - "base" graphics
  - "grid" graphics
  - See *R Graphics* by Paul Murrell for a very thorough "deep-dive" into these implementations:  https://www.stat.auckland.ac.nz/~paul/RG2e/

### Base graphics
  - more "primitive"
  - can also be much faster than grid
  - lots of isolated plot functions
  - lots of weird little parameters to worry about
  - some handy quick-plot functions from base graphics:
    - `plot()` : a generic function that will often produce something interesting, can do scatterplots with a formula `x ~ y`
    - `hist()` : histogram of a vector
    - `boxplot()` : boxplot, using a formula `variable ~ grouping.factor`

### Grid graphics
  - better for more "high-level" plots
  - much more complex underlying system (IMHO)
  - more powerful and extendable
  - the basis of extremely popular packages such as `lattice` and `ggplot2`

## Graphics packages

  - many packages will have some kind of graphics functions in them, for visualizing specific kinds of things
  - these will often be in base graphics, "pre-canned", etc.
  - the two best more general-purpose graphics packages are `lattice` and `ggplot2`
  - `ggplot2` is another Hadley Wickham project, and has the most documentation, examples, and is currently most widely used

# Using `ggplot2`

## A "Grammar of Graphics"
  - based on work by Leland Wilkinson, a "theory" of graphic display of data
  - Hadley implemented this framework as his dissertation
  - `ggplot` is the overhauled version of the original implementation, and it is still under active development
  - the idea is to implement a general system for mapping data variables to *aesthetics* (Wilkinson's term), i.e., visual dimensions (x, y, color, etc.)
  - allows for high-level control of the structure of a plot, to allow for flexible, powerful visualizations
  
## Basic structure and concepts

  - unlike base graphics, the *value* of `ggplot2` objects is a complex object, and `print()`-ing them renders the graph.
  - the value of the object is built up by adding *layers*
  - start with a call to `ggplot()` that specifies the data and some mappings of variables to aesthetics
  - add "geoms" to actually render something
  - add other things for fine control over graphical parameters, etc.

## Graphing the `iris` package

# Practice 5

# Review Practice 5

# Admin round-up

## Weekend homework

## Project proposals due!

## My flight schedule and Plan B